apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

components:
  - ../../variants/non-prod
  - ../../variants/eu

patchesStrategicMerge:
- deployment.yml
- version.yml
- replicas.yml

