apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: load
namePrefix: load-gpu-

resources:
- ../../base

components:
  - ../../variants/non-prod

patchesStrategicMerge:
- deployment.yml
- version.yml
- replicas.yml
- settings.yml

